services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql